"""
calibration_constants.py — Auto-generated by fit_thermal.py
Generated: 2026-03-11T12:55:47.321302

These constants are correction factors measured on REAL SILICON (ATmega328P)
and applied to all thermal/electrical simulations.

Factor = measured_on_silicon / datasheet_value
  >1.0 → real chip is worse than spec (conservative)
  <1.0 → real chip is better than spec
"""

# Thermal RC model corrections
R_THETA_CORRECTION     = 0.9951   # measured/published R_theta
C_THERMAL_CORRECTION   = 0.9785  # measured/reference C_thermal
TAU_CORRECTION         = 0.9737   # measured/expected tau

# Power model corrections  
POWER_CORRECTION       = 1.0000   # actual/assumed power

# Source chip
CALIBRATED_ON          = "ATmega328P_DIP28"
CALIBRATION_R_MEASURED = 67.67   # °C/W measured
FIT_QUALITY            = "EXCELLENT"

def apply_thermal(r_theta: float) -> float:
    """Apply correction to any R_theta estimate."""
    return r_theta * R_THETA_CORRECTION

def apply_power(p_w: float) -> float:
    """Apply correction to power estimate."""
    return p_w * POWER_CORRECTION
